<!--
	The Thumb Butte mark: the butte against a sunset sky, framed by AF corner
	brackets. Paths are generated by brand/generator/build.py; colours come
	from the theme tokens, so it follows light and dark.
-->
<script lang="ts">
	import { mark } from '#lib/brand/mark.ts';

	let { label }: { label?: string } = $props();
</script>

<svg
	class="logo"
	viewBox="0 0 200 200"
	role={label ? 'img' : undefined}
	aria-label={label}
	aria-hidden={label ? undefined : 'true'}
>
	<path class="brackets" d={mark.brackets} />
	<path class="butte" d={mark.butte} />
	<path class="sky" d={mark.sky} />
</svg>

<style>
	.logo {
		display: block;
		flex: none;
	}
	.brackets {
		fill: var(--color-text);
	}
	.butte {
		fill: var(--color-logo-butte);
	}
	.sky {
		fill: var(--color-accent);
	}
</style>
